name: EK Photographic
favicon: null
layout_spectrum: 0.7973073513712734
typography_spectrum: 0.26766301901079714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07150925742462277
  lightness: 0.6432138956151903
  saturation: 0.2817921992391348
  rhythmicContrast: 0.21943512558937073
purpose: []
